name: PageSpeed Insights Audit

on: 
  push:
    branches:
    - main
  schedule:
    - cron:  '0 13 * * 6'
  repository_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights (Mobile)
        uses: mattorb/psi-action@v1
        id: psi_mobile
        with:
          url: "https://woodstickers.com"
          threshold: 50
          strategy: mobile
      - name: Running Page Speed Insights (Desktop)
        uses: mattorb/psi-action@v1
        id: psi_desktop
        with:
          url: "https://woodstickers.com"
          threshold: 50
          strategy: desktop